### ISSUE TITLE
Avoid relative abundances for vertebrates

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/StratigraphicDiagrammer#3]
Faunal assemblages should not be displayed as relative abundances (%) - should simply display each taxon in original counts (MNI, NISP, etc).  Relative abundances mainly used for micropaleontological data (pollen, forams, diatoms, ostracodes, etc.)

**Comment by stryker-m** [comment]
precedence now:  if vertebrate fauna preference present/absent, else preference NISP, otherwise first available VariableUnit
