### ISSUE TITLE
Y-axis:  Avoid Radiocarbon Ages when possible.

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/StratigraphicDiagrammer#5]
Y-axis should always default to Calibrated Ages over Radiocarbon Ages.  Radiocarbon Ages preferred over Depth.

**Comment by stryker-m** [comment]
This rule can be applied.  Each available age will have an AgeType.  If no Ages available, depth will be selected.

**Comment by stryker-m** [comment]
precedence now: 1) has DefaultChronID, 2) has AgeType "Calendar years BP",  3) has Depth, 4) first age found
